org: renatolomba20
app: image-analysis
service: image-analysis
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - rekognition:DetectLabels
        Resource: "*"
      - Effect: Allow
        Action:
          - translate:TranslateText
        Resource: "*"

functions:
  image-analysis:
    handler: dist/index.main
    events:
      - httpApi:
          path: /analyse
          method: get
