service: lambda-environment-schedulers

frameworkVersion: '3'

plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    NODE_ENV: ${opt:stage, "dev"}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
