service: trigger-dynamodb

frameworkVersion: '3'

plugins:
  - serverless-jetpack
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    HEROES_TABLE: ${self:custom.heroesTableName}
    NODE_ENV: ${opt:stage, "dev"}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:PutItem
            - dynamodb:Select
            - dynamodb:Attributes
            - dynamodb:ReturnConsumedCapacity
            - dynamodb:ListStreams
            - dynamodb:DescribeStream
            - dynamodb:Scan
          Resource: ${self:custom.heroesTableArn}

resources:
  Resources:
    HeroesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.heroesTableName}-${opt:stage, "dev"}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
  hero-trigger:
    handler: dist/trigger.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - HeroesTable
              - StreamArn

custom:
  heroesTableArn: !GetAtt HeroesTable.Arn
  heroesTableName: Heroes
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
    docker:
      sudo: False
